### ISSUE TITLE
Defining synonyms in json configuration

### ISSUE THREAD

**Issue by JanTvrdik** [mvoidex/UnicodeMath#1]
I really like the idea of synonyms for some symbols, so I would like to define my own synonyms in json configuration for symbols I frequently use. For example

``` json
{
    "alpha": "upalpha",
    "beta": "upbeta",
    "gamma": "upgamma",
    "delta": "updelta",
    "epsilon": "upepsilon",
    "eps": "upepsilon",
    "lambda": "uplambda",
    "union": "cup",
    "intersect": "cap"
}
```

**Comment by medovina** [comment]
This feature is great, however it should be documented on the project home page.  As far as I can tell, at the moment the only way to discover it is to read this closed bug.
