### ISSUE TITLE
Can't input \x -> foobar

### ISSUE THREAD

**Issue by ulidtko** [mvoidex/UnicodeMath#10]
While the plugin is active, I can't type an anonymous function `(\x -> x + 1)` in Haskell syntax -- because UnicodeMath unconditionally converts that to the cross product symbol `×`.

**Comment by mvoidex** [comment]
`shift+space` can be used to insert space, or `\ x` can be used instead of `\x`, or we can just remove `x` synonym, but I don't know if `\x` is widely used to insert `×`
