### ISSUE TITLE
Cannot underscore some letters

### ISSUE THREAD

**Issue by mbiokyle29** [mvoidex/UnicodeMath#12]
For some reason I cannot seem to subscript some characters.
For example `\_f` does not produce a sub scripted `f`. Same seems to apply for `\_d` `\_w` and others.

I am on Ubuntu 14.04, Sublime build 3083

**Comment by mvoidex** [comment]
I've got list of subscript and superscript symbols from Wikipedia (https://en.wikipedia.org/wiki/Superscripts_and_Subscripts). I don't know if there such a symbol for subscript f, does it exist?

**Comment by mbiokyle29** [comment]
My apologies, I did not realize the reason I could not make f underscore was due to the fact that such a character does not exist in unicode. Sorry to bother you, and thanks for some an awesome package!

**Comment by mvoidex** [comment]
Ok, np
