### ISSUE TITLE
documentation recommendation - supported fonts

### ISSUE THREAD

**Issue by gatapia** [mvoidex/UnicodeMath#13]
Awesome ST package, really making my life easier with some math documentation.

A couple of recommendations and questions for the documentation:
- what font is recommended, tried a few and get missing boxes for a lot of math symbols and some symbols do not show well using Tahoma, Arial, Consolas. 
- Would love to see a table of all the alias supported with their corresponding math symbols

Thanks again for a great package

**Comment by mvoidex** [comment]
Thanks for review

I'm using these options on Windows:

	// Many unicode symbols
	"font_face": "Lucida Sans Unicode",
	// This option enables font-substitution for unknown unicode symbols
	"font_options":
	[
		"directwrite"
	],

> Would love to see a table of all the alias supported with their corresponding math symbols
Good idea, I'll add markdown file with table for symbols and synonyms.

**Comment by mvoidex** [comment]
Updates to readme:
[Font setting section](https://github.com/mvoidex/UnicodeMath#font-settings)
[Table with symbols](https://github.com/mvoidex/UnicodeMath/blob/master/table.md)

**Comment by gatapia** [comment]
thats awesome, thanks
