### ISSUE TITLE
Some symbols are not displayed properly

### ISSUE THREAD

**Issue by samizel** [mvoidex/UnicodeMath#15]
Hello,

I'm facing the problem that some symbols are not displayed properly. 

![image](https://cloud.githubusercontent.com/assets/7371313/14672720/e4d91e22-06f9-11e6-9060-a6e631bf3ccd.png)

Greetings
samizel

**Comment by mvoidex** [comment]
Have you tried this https://github.com/mvoidex/UnicodeMath#font-settings?

**Comment by samizel** [comment]
Yeah that was the problem. Thank you!
