### ISSUE TITLE
Subscript for many letters not working

### ISSUE THREAD

**Issue by minimcloving** [mvoidex/UnicodeMath#18]
#Whenever i try to use "y", and many other letters, as a subscript, it doesnt seem to conver.
If I type in "\_y" and press space or tab, it doesn't convert the letter. I dont know why this is happening because it seems to work for many other conversions.

Thank you

**Comment by mvoidex** [comment]
As I know, there's no such symbol:
https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts
If you find it, tell me code, I'll insert it into table

**Comment by minimcloving** [comment]
Alexandr,

Thank you for the reply. I was trying to make a physics equation sheet for a class I am in but I will probably just be using LaTeX for this documentation. Love your software though, thank you very much.

Sincerely,
Armand Alvarez

**Comment by mvoidex** [comment]
Thanks :)
