### ISSUE TITLE
Auto-completion is not working on Sublime Text 3 (Mac 10.12)

### ISSUE THREAD

**Issue by trinhngocthuyen** [mvoidex/UnicodeMath#20]
Hello!
I am using this package on Sublime Text 3 (Mac 10.12.3).
And it seems auto-completion is not working as demonstrated in README. Typing `\a` and no completion panel was prompted.
P/s: The replacement actually works because it can replace `\all ` (ie: `\all + spacing`) by the corresponding math symbol.

Is the completion feature supported for Mac? Or is there any further configuration I have to manually set?
Thanks!

**Comment by mvoidex** [comment]
What syntax is enabled in your case?
I'm not sure, why, but popup isn't shown automatically for text syntaxes (`Plain Text`, `Markdown`, maybe some other), and autoshown on language syntaxes (`c++`, `haskell`, `python`...)
Ctrl+space can force showing completion list (insert '\' and press ctrl+space)

**Comment by trinhngocthuyen** [comment]
Oh, I got it. It was Markdown that I used. I was assuming it worked for Plain text and Markdown as well.
Thanks a lot!

**Comment by mbforbes** [comment]
Sorry to add to a closed issue, but I'm also having this issue, both on macOS and Ubuntu. The completions seem to happen in exactly the opposite environments than I want them to — they don't work in plain text, markdown, or code comments (e.g., C++), but they do work in the actual code (e.g., C++) itself!

I looked in the settings for this plugin and don't see anything relevant to configure. Any advice?

**Comment by serg06** [comment]
Can the package have its own syntax that behaves just like plaintext but has auto-completion working?

Also, can you add this "quirk" to the README.md? I have already quit this plugin many times over the years because I just couldn't get auto-completion to work. (Until today, when I tried yaml instead of plain text.)

**Comment by marcusrettig** [comment]
Adding this to syntax specific settings (txt, markdown etc.) made it work for me ([reference](https://forum.sublimetext.com/t/autocomplete-suggestions-do-not-automatically-appear/24129/3)).
```
"auto_complete_selector": "text, comment, string, meta.tag - punctuation.definition.tag.begin, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc"
```
