### ISSUE TITLE
Could you update the read me with how to install the plugin.

### ISSUE THREAD

**Issue by vikasnar** [mvoidex/UnicodeMath#21]
Hi, could you please update the readme with setup instructions.

**Comment by mvoidex** [comment]
Will link to [PackageControl](https://packagecontrol.io/) be enough?

**Comment by LandisTwo** [comment]
I could Not install via Package Control. 2019.01.25
I get the following error:
---
"SublimeText", "SyntaxFold", "UnicodeMath", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/mvoidex/UnicodeMath/zip/master.
error: Package Control
---
Unable to download UnicodeMath. Please view the console for more details.
===
please update cert.. i'd really like to use your plug-in.
----
ps. i'm still using ST3, build 3176. i do Not like the look of newer vers. just like i will Never user KDE 'plasma 5'... very ugly.

thanks, Landis.

**Comment by mvoidex** [comment]
Hi! github.com is not my host :) I can't update any certs there

**Comment by mvoidex** [comment]
Readme updated
