### ISSUE TITLE
mith missing

### ISSUE THREAD

**Issue by kebman** [mvoidex/UnicodeMath#22]
`\mith` is missing. You can find `\mitg` and `\miti` but not `\mith`. Might be prudent to check if more are missing too.

**Comment by mvoidex** [comment]
Seems, that there's no such unicode symbol:
https://unicode-table.com/en/search/?q=Mathematical+Italic+Small

As you can see, `g` is `U+1D454` and `i` is `U+1D456`.
I've tried `U+1D455` (`\U0001D455`), but it's converted to `𝑕`

**Comment by kebman** [comment]
D'oh! Why didn't I think of checking Unicode! :) U+1D455 comes up as \<Reserved\> at Unicode ( https://unicode-table.com/en/1D455/ ), but a related character is the Planck Constant U+210E, and it is suggested as a valid substitution.

As can be seen from this list, several glyphs are missing: https://unicode-table.com/en/blocks/mathematical-alphanumeric-symbols/

If you check this one, you'll see valid substitutions for missing glyphs: https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols

Did some further digging and found this: https://stackoverflow.com/questions/9790662/reserved-character-codes-in-unicode

Hope this helps!
