### ISSUE TITLE
Autocomplete only on tab option? (instead of space)

### ISSUE THREAD

**Issue by amccaugh** [mvoidex/UnicodeMath#24]
Great plugin, but I wanted to know if we could add a user option to disallow the space button from autocompleting?  Sublime by itself only autocompletes when using the "enter" or "tab" keys, so allowing space to autocomplete is a departure from that method.

I understand that there is a "shift-space" operation, but it's definitely more annoying to have to remember that specific exception for UnicodeMath than to just be able to type with space and not think about it!

**Comment by mvoidex** [comment]
I'll add config on weekend

**Comment by mvoidex** [comment]
You can set `convert_on_space` to false to disable auto-conversion.
