### ISSUE TITLE
subscript not working for multiple characters and superscript nor working on any 

### ISSUE THREAD

**Issue by pearthehuman** [mvoidex/UnicodeMath#25]
I can only get subscript to work for single characters and only by '\\_n' + tab , can't do multiple characters. 

Additionally I cannot seem to get any characters to work with superscript.

I am using the default settings unmodified. 

Thank you :)

**Comment by mvoidex** [comment]
Try `\_nm + space` and `\^nm + space`

**Comment by garrettdowd** [comment]
I am also having similar problems with subscripts for some letters. Subscript does not work for "y,d,f,g,z,c, and b" or any combination of characters with at least one of the aforementioned characters.

Default settings. I disabled other packages I have installed. Not sure what else to try.

**Comment by mvoidex** [comment]
As previously mentioned, not all characters available for sub- and superscript.
Feel free to reopen if it's not your case.
