### ISSUE TITLE
Support for Mathematical Double Struck Capital? 

### ISSUE THREAD

**Issue by kevin931** [mvoidex/UnicodeMath#29]
Is there support for double struck capitals to represent useful symbols, such as those for reals (U+211D), integers (U+2124), etc.? I didn't seem to be able find these in the table provided (or maybe they are under different name).

**Comment by mariohuq** [comment]
Search for BbbR [here](https://github.com/mvoidex/UnicodeMath/blob/master/table.md)

**Comment by kevin931** [comment]
Awesome! Thank you so much! This is exactly what I need! (Apologies for not finding this on my own...)
