### ISSUE TITLE
Subscript with capital letter

### ISSUE THREAD

**Issue by joshuageorgepa** [mvoidex/UnicodeMath#34]
<img width="207" alt="Screen Shot 2022-02-24 at 5 09 26 PM" src="https://user-images.githubusercontent.com/79168709/155634352-3a423135-8ccf-4b6d-b0e7-0ae5489cd9d0.png">

Is it possible to do subscript with capital letters as shown in the attached image? 
[1_{R_1}]

Please let me know.

**Comment by mvoidex** [comment]
Hi! No, it's not possible. This plugin doesn't affect rendering symbols, it's just input method for existing unicode symbols and there's no sub-substrict 1.
