### ISSUE TITLE
Option to insert instantly when not ambiguous?

### ISSUE THREAD

**Issue by lephe** [mvoidex/UnicodeMath#36]
First of all, I really love this package, thank your for keeping it up. :D

A very efficient behavior I've found on other editors is to insert escapes more eagerly in two situations:

1. When an escape is complete: if I type `\alpha` then it is substituted with `α` as soon as I type the last `a`. (If I don't want to substitute, I can undo.)
2. When an escape is unambiguous: if I type `\alp` and then some character X such that there is no escape called `\alpX` (and the only symbol that starts with `\alp` is `\alpha`), then it inserts `αX`.

Both are really useful because they reduce the amount of spaces and characters to type. For users of math-formalization languages like me where escapes are *everywhere*, it's a huge plus.

I think an option to enable such behavior (off by default) would be helpful. I can try and work it out, but is that fine with you at least?

**Comment by mvoidex** [comment]
Hi! Looks as nice feature :)

> is that fine with you at least?

Yes, completely
