### ISSUE TITLE
subscript not always working

### ISSUE THREAD

**Issue by IlyaBokovenko** [mvoidex/UnicodeMath#38]
Hello. Not all letters can be subscripted. For instance I can subscript 'a' by typing \\_a but I can't subscript 'b', 'w' and many other letters

**Comment by mvoidex** [comment]
Hi. That's because there're no such unicode symbols, see [wikipedia](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin,_Greek_and_Cyrillic_tables) for details

Related issue: #40
