### ISSUE TITLE
Alphabetic characters as sub/superscripts

### ISSUE THREAD

**Issue by rtalexander** [mvoidex/UnicodeMath#40]
I suggest you add a list of lowercase alphabetic characters that can be converted to subscripts and superscripts. The following might be suitable:

The following alphabetic characters can be rendered as subscripts in Unicode:

	a,e,h,i,j,k,l,m,n,o,p,r,s,t,u,v,x,

These cannot:

	b,c,d,f,g,,q,w,y,z

**Comment by mvoidex** [comment]
That's because there're no unicode symbol for these subscripts, see [wikipedia](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin,_Greek_and_Cyrillic_tables) for details

**Comment by mvoidex** [comment]
closing issue

**Comment by mvoidex** [comment]
That's because there're no unicode symbols for these subscripts, see [wikipedia](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin,_Greek_and_Cyrillic_tables) for details
